@startuml
'https://plantuml.com/sequence-diagram
'Diagrama de secuencia, se puede renderizar instalando el plugin PlantUML de IntelliJ

autonumber

Main ->> Creador: run
Main ->> Mejorador : run
Main ->> Ajustadores : run
Main ->> Movedores : run

par
Creador -> Imagen: <<create>>
Creador  <-- Imagen


critical
Creador -> ContenedorInicial : agregarImagen
Creador <-- ContenedorInicial
end critical






loop this.mejoradas < 100
critical

Mejorador -> ContenedorInicial : getImagen

ContenedorInicial --> Mejorador

end critical

alt !this.ImagenesRevisadas[imagen.getName()]
Mejorador -> ContenedorInicial :setImagenMejorada
ContenedorInicial --> Mejorador

end alt
end loop



Ajustadores -> ContenedorInicial : getImagenesAjustadas
ContenedorInicial --> Ajustadores

loop this.ContenedorInicial.getImagenesAjustadas() < 100

critical

Ajustadores -> ContenedorInicial : getImagen
ContenedorInicial --> Ajustadores
end critical

alt imagen.getImprovements() == 3 && imagen.setResize(true)
Ajustadores  -> ContenedorInicial: setImagenAjustada
ContenedorInicial --> Ajustadores
end alt


end loop




Movedores -> ContenedorInicial: getImagenesEliminadas
ContenedorInicial --> Movedores

loop this.ContenedorInicial.getImagenesEliminadas() < 100

critical
Movedores -> ContenedorInicial : getImagen
ContenedorInicial --> Movedores
end critical

alt imagen.getImprovements() == 3 && imagen.getResize()

critical
Movedores -> ContenedorFinal : agregarImagen
ContenedorFinal --> Movedores
Movedores -> ContenedorInicial : eliminarImagen
ContenedorInicial --> Movedores
Movedores -> ContenedorInicial : setImagenEliminada
ContenedorInicial --> Movedores
end critical

end alt

end loop

end par

@enduml